### ISSUE TITLE
Cannot create a model object with image

### ISSUE THREAD

**Issue by vitulicny** [wearefine/fae#344] opened 2017-11-03 18:56 UTC
I try to create an object with an image, but always get this error.

I have fresh RoR app with Fae gem. Fae was initialized and Article model generated via Fae scaffold.

Any ideas what to check pls?

<img width="1280" alt="screenshot 2017-11-03 19 49 13" src="https://user-images.githubusercontent.com/1032403/32391003-ce1c735e-c0d0-11e7-8bc6-9764b312adc4.png">

Terminal:
```Started POST "/admin/articles" for 127.0.0.1 at 2017-11-03 19:49:09 +0100
Processing by Admin::ArticlesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"bhy+1bnj26ygcZTDgDEcMGPhZUJg1CrNzUIww93kDThZvtYBPufix3I4GkilsFm6a/8dTlIzKSbtY0MEV5iL8w==", "commit"=>"Save", "article"=>{"title"=>"afds", "hero_image_attributes"=>{"asset_cache"=>"1509734813-46861-1660/Screenshot_2017-11-03_15.24.20.png", "imageable_type"=>"Article", "attached_as"=>"hero_image", "alt"=>"fds", "required"=>"false"}}}
  Fae::User Load (0.6ms)  SELECT "fae_users".* FROM "fae_users" INNER JOIN "fae_roles" ON "fae_roles"."id" = "fae_users"."role_id" WHERE "fae_users"."active" = $1 AND "fae_roles"."name" = $2 ORDER BY "fae_users"."first_name" ASC, "fae_users"."last_name" ASC  [["active", "t"], ["name", "super admin"]]
  Fae::User Load (0.4ms)  SELECT  "fae_users".* FROM "fae_users" WHERE "fae_users"."id" = $1 ORDER BY "fae_users"."first_name" ASC, "fae_users"."last_name" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Fae::Option Load (0.5ms)  SELECT  "fae_options".* FROM "fae_options" ORDER BY "fae_options"."id" ASC LIMIT $1  [["LIMIT", 1]]
  Fae::Role Load (0.4ms)  SELECT  "fae_roles".* FROM "fae_roles" WHERE "fae_roles"."id" = $1 ORDER BY -position DESC LIMIT $2  [["id", 1], ["LIMIT", 1]]
   (0.2ms)  BEGIN
   (0.2ms)  ROLLBACK
  Rendering admin/articles/new.html.slim within layouts/fae/application
  Rendered /Users/vitek/.rvm/gems/ruby-2.4.2/gems/fae-rails-1.6.0/app/views/fae/application/_breadcrumb.html.slim (4.1ms)
  Rendered /Users/vitek/.rvm/gems/ruby-2.4.2/gems/fae-rails-1.6.0/app/views/fae/shared/_form_header.html.slim (25.4ms)
  Rendered /Users/vitek/.rvm/gems/ruby-2.4.2/gems/fae-rails-1.6.0/app/views/fae/application/_flash_messages.slim (3.6ms)
  Rendered /Users/vitek/.rvm/gems/ruby-2.4.2/gems/fae-rails-1.6.0/app/views/fae/shared/_errors.slim (18.6ms)
  Rendered /Users/vitek/.rvm/gems/ruby-2.4.2/gems/fae-rails-1.6.0/app/views/fae/images/_image_uploader.html.slim (11.5ms)
  Rendered admin/articles/_form.html.slim (75.7ms)
  Rendered admin/articles/new.html.slim within layouts/fae/application (80.5ms)
  Fae::Image Load (0.5ms)  SELECT  "fae_images".* FROM "fae_images" WHERE "fae_images"."imageable_id" = $1 AND "fae_images"."imageable_type" = $2 AND "fae_images"."attached_as" = $3 LIMIT $4  [["imageable_id", 1], ["imageable_type", "Fae::Option"], ["attached_as", "favicon"], ["LIMIT", 1]]
  Rendered /Users/vitek/.rvm/gems/ruby-2.4.2/gems/fae-rails-1.6.0/app/views/fae/application/_mobilenav.slim (12.8ms)
  Rendered /Users/vitek/.rvm/gems/ruby-2.4.2/gems/fae-rails-1.6.0/app/views/fae/application/_global_search_results.html.slim (5.6ms)
  Rendered /Users/vitek/.rvm/gems/ruby-2.4.2/gems/fae-rails-1.6.0/app/views/fae/application/_header.slim (34.3ms)
  Rendered /Users/vitek/.rvm/gems/ruby-2.4.2/gems/fae-rails-1.6.0/app/views/fae/application/_sidenav.slim (8.0ms)
  Rendered /Users/vitek/.rvm/gems/ruby-2.4.2/gems/fae-rails-1.6.0/app/views/fae/application/_credit.slim (9.3ms)
  Rendered /Users/vitek/.rvm/gems/ruby-2.4.2/gems/fae-rails-1.6.0/app/views/fae/application/_markdown_helper.slim (7.6ms)
Completed 200 OK in 387ms (Views: 372.4ms | ActiveRecord: 2.8ms)


Started GET "/Users/vitek/Documents/code/smazme/myapp/tmp/fae/uploads/1509734813-46861-1660/Screenshot_2017-11-03_15.24.20.png" for 127.0.0.1 at 2017-11-03 19:49:10 +0100
  
ActionController::RoutingError (No route matches [GET] "/Users/vitek/Documents/code/smazme/myapp/tmp/fae/uploads/1509734813-46861-1660/Screenshot_2017-11-03_15.24.20.png"):
  
actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.4) lib/rails/engine.rb:522:in `call'
puma (3.10.0) lib/puma/configuration.rb:225:in `call'
puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
puma (3.10.0) lib/puma/server.rb:437:in `process_client'
puma (3.10.0) lib/puma/server.rb:301:in `block in run'
puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by jamesmk** [comment] 2017-11-03 19:57
@vitulicny Can you share your `schema.rb`, `Article` model and controller?

**Comment by vitulicny** [comment] 2017-11-03 20:45
```module Admin
  class ArticlesController < Fae::BaseController

    private

    def build_assets
      @item.build_hero_image if @item.hero_image.blank?
    end

  end
end
```

```
ActiveRecord::Schema.define(version: 20171103184617) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "articles", force: :cascade do |t|
    t.string "title"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "fae_changes", force: :cascade do |t|
    t.integer "changeable_id"
    t.string "changeable_type"
    t.integer "user_id"
    t.string "change_type"
    t.text "updated_attributes"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["changeable_id"], name: "index_fae_changes_on_changeable_id"
    t.index ["changeable_type"], name: "index_fae_changes_on_changeable_type"
    t.index ["user_id"], name: "index_fae_changes_on_user_id"
  end

  create_table "fae_files", force: :cascade do |t|
    t.string "name"
    t.string "asset"
    t.string "fileable_type"
    t.bigint "fileable_id"
    t.integer "file_size"
    t.integer "position", default: 0
    t.string "attached_as"
    t.boolean "on_stage", default: true
    t.boolean "on_prod", default: false
    t.boolean "required", default: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["attached_as"], name: "index_fae_files_on_attached_as"
    t.index ["fileable_type", "fileable_id"], name: "index_fae_files_on_fileable_type_and_fileable_id"
  end

  create_table "fae_images", force: :cascade do |t|
    t.string "name"
    t.string "asset"
    t.string "imageable_type"
    t.bigint "imageable_id"
    t.string "alt"
    t.string "caption"
    t.integer "position", default: 0
    t.string "attached_as"
    t.boolean "on_stage", default: true
    t.boolean "on_prod", default: false
    t.integer "file_size"
    t.boolean "required", default: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["attached_as"], name: "index_fae_images_on_attached_as"
    t.index ["imageable_type", "imageable_id"], name: "index_fae_images_on_imageable_type_and_imageable_id"
  end

  create_table "fae_options", force: :cascade do |t|
    t.string "title"
    t.string "time_zone"
    t.string "colorway"
    t.string "stage_url"
    t.string "live_url"
    t.integer "singleton_guard"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["singleton_guard"], name: "index_fae_options_on_singleton_guard", unique: true
  end

  create_table "fae_roles", force: :cascade do |t|
    t.string "name"
    t.integer "position"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "fae_static_pages", force: :cascade do |t|
    t.string "title"
    t.integer "position", default: 0
    t.boolean "on_stage", default: true
    t.boolean "on_prod", default: false
    t.string "slug"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["slug"], name: "index_fae_static_pages_on_slug"
  end

  create_table "fae_text_areas", force: :cascade do |t|
    t.string "label"
    t.text "content"
    t.integer "position", default: 0
    t.boolean "on_stage", default: true
    t.boolean "on_prod", default: false
    t.integer "contentable_id"
    t.string "contentable_type"
    t.string "attached_as"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["attached_as"], name: "index_fae_text_areas_on_attached_as"
    t.index ["contentable_id"], name: "index_fae_text_areas_on_contentable_id"
    t.index ["contentable_type"], name: "index_fae_text_areas_on_contentable_type"
    t.index ["on_prod"], name: "index_fae_text_areas_on_on_prod"
    t.index ["on_stage"], name: "index_fae_text_areas_on_on_stage"
    t.index ["position"], name: "index_fae_text_areas_on_position"
  end

  create_table "fae_text_fields", force: :cascade do |t|
    t.string "contentable_type"
    t.bigint "contentable_id"
    t.string "attached_as"
    t.string "label"
    t.string "content"
    t.integer "position", default: 0
    t.boolean "on_stage", default: true
    t.boolean "on_prod", default: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["attached_as"], name: "index_fae_text_fields_on_attached_as"
    t.index ["contentable_type", "contentable_id"], name: "index_fae_text_fields_on_contentable_type_and_contentable_id"
    t.index ["on_prod"], name: "index_fae_text_fields_on_on_prod"
    t.index ["on_stage"], name: "index_fae_text_fields_on_on_stage"
    t.index ["position"], name: "index_fae_text_fields_on_position"
  end

  create_table "fae_users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer "sign_in_count", default: 0, null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string "current_sign_in_ip"
    t.string "last_sign_in_ip"
    t.string "confirmation_token"
    t.datetime "confirmed_at"
    t.datetime "confirmation_sent_at"
    t.string "unconfirmed_email"
    t.integer "failed_attempts", default: 0, null: false
    t.string "unlock_token"
    t.datetime "locked_at"
    t.string "first_name"
    t.string "last_name"
    t.integer "role_id"
    t.boolean "active"
    t.string "language"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["confirmation_token"], name: "index_fae_users_on_confirmation_token", unique: true
    t.index ["email"], name: "index_fae_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_fae_users_on_reset_password_token", unique: true
    t.index ["role_id"], name: "index_fae_users_on_role_id"
    t.index ["unlock_token"], name: "index_fae_users_on_unlock_token", unique: true
  end

end
```

**Comment by jamesmk** [comment] 2017-11-03 20:54
Thanks @vitulicny, could I see the model too?

**Comment by vitulicny** [comment] 2017-11-03 22:57
@jamesmk 
```
class Article < ApplicationRecord
  include Fae::BaseModelConcern

  def fae_display_field
    title
  end

  has_fae_image :hero_image


end
```

**Comment by jamesmk** [comment] 2017-11-03 23:32
Well that's about as straight forward as is gets. My guess is there is an issue with saving the asset locally. One of the SQL calls is rolling back, so the first thing I'd look into is if there are any errors on your object when you try to save it.

You could attempt it manually in the console or you debug it directly in the controller. `ArticlesController` inherits it's methods from `Fae::BaseController` (https://github.com/wearefine/fae/blob/master/app/controllers/fae/base_controller.rb), so you could override the `create` method with a bedugger of your choice:

```ruby
class ArticlesController < Fae::BaseController

    def create
      return create_from_existing(params[:from_existing]) if params[:from_existing].present?
      @item = @klass.new(item_params)
      byebug # or raise, binding.pry, etc
    end

    private

    def build_assets
      @item.build_hero_image if @item.hero_image.blank?
    end

  end
end
```

Then attempt to save in the shell and see what error it returns:

```
> @item.save
> @item.errors.messages
```

Let me know if there are any useful errors that identify an issue.

thanks

**Comment by timshingyu** [comment] 2017-11-04 15:31
I have encountered the same issue before. My case is related to saving the nested object in rails 5.

To fix this, you can try to add these files to override the fae ones

**app/models/fae/file.rb**
```
require 'file_size_validator'

module Fae
  class File < ActiveRecord::Base

    include Fae::BaseModelConcern
    include Fae::FileConcern
    include Fae::AssetsValidatable

    mount_uploader :asset, Fae::FileUploader

    validates :asset,
              file_size: {
                  maximum: Fae.max_file_upload_size.megabytes.to_i
              }

    belongs_to :fileable, polymorphic: true, touch: true, optional: true

    def readonly?
      false
    end

  end
end
```

**app/models/fae/image.rb**
```
require 'file_size_validator'

module Fae
  class Image < ActiveRecord::Base

    include Fae::BaseModelConcern
    include Fae::ImageConcern
    include Fae::AssetsValidatable

    attr_accessor :redirect
    mount_uploader :asset, Fae::ImageUploader

    after_save :recreate_versions

    validates :asset,
              file_size: {
                  maximum: Fae.max_image_upload_size.megabytes.to_i
              }

    belongs_to :imageable, polymorphic: true, touch: true, optional: true

    def readonly?
      false
    end

    private

    def recreate_versions
      asset.recreate_versions! if Fae.recreate_versions && asset.present?
    end

  end
end
```

You can read this post for more info:
http://jarlowrey.com/blog/polymorphic-rails-5.html

**Comment by vitulicny** [comment] 2017-11-04 19:10
@timshingyu It is working with your fix :) Thanks a lot :) 

Do you know why this optional: true fix it?

**Comment by jamesmk** [comment] 2017-11-05 06:49
Awesome, glad that worked!

@vitulicny @timshingyu What Rails versions were you seeing this issue in? I'd like to recreate it so I can verify the solution and roll it into the source

thanks

**Comment by vitulicny** [comment] 2017-11-05 09:03
@jamesmk 
Rails version: 5.1.4

**Comment by timshingyu** [comment] 2017-11-05 15:29
@vitulicny It seem the bug in rails 5 [bug](https://github.com/rails/rails/issues/29781)
@jamesmk Mine is 5.1.4

**Comment by tenshiAMD** [comment] 2017-11-09 02:21
I think this might be the problem: https://github.com/wearefine/fae/blob/master/app/models/concerns/fae/base_model_concern.rb#L84-L90.

There is a bug in rails 5 where `inverse_of` does not applied automatically in association like `has_many` and might be also a issue in `belongs_to` and `has_one`. (See issue  https://github.com/rails/rails/issues/25198)

A possible workaround is to override the method `has_fae_image` is to add `inverse_of` option.

```
def has_fae_image(image_name_symbol)
   has_one image_name_symbol, -> { where(attached_as: image_name_symbol.to_s) },
      as: :imageable,
      inverse_of: :imageable,
      class_name: '::Fae::Image',
      dependent: :destroy
   accepts_nested_attributes_for image_name_symbol, allow_destroy: true
end
```

**Comment by jamesmk** [comment] 2017-11-14 08:00
Since this appears to be a Rails 5.1 bug, I'll look to get it fixed in Fae v2, which we are targeting by EOY. We currently don't support Rails 5.1 in Fae v1 as the effort to support both Rails 4 and 5.1 is too great.

**Comment by jamesmk** [comment] 2018-04-14 00:11
Working on fix now, but closing this one as it's a duplicate of #246

**Closed by jamesmk** 2018-04-14 00:11 UTC
Labels: Rails 5.1
