### ISSUE TITLE
Ajax response bug in nested form with image

### ISSUE THREAD

**Issue by nlively** [wearefine/fae#436] opened 2018-10-20 19:21 UTC
I have a parent model form with nested table/form for a child model.  The child model has an image field.  I am able to add a new child from the form and save it.  The new child is persisted to the database but the form doesn't disappear and get replaced by the table.

This is the error I get:
`Uncaught TypeError: $html.hasClass is not a function`

Seems to be coming from line 127 of this file:
`app/assets/javascripts/fae/form/_ajax.js`

**Comment by jamesmk** [comment] 2018-10-26 16:16
Thanks for the bug report. `hasClass` is a jQuery function, so there might be an issue or conflict with the dependency. I cannot reproduce this in the dummy or test site. Is there anyway you can post an example app with this issue?

**Comment by Shigawire** [comment] 2018-12-28 13:43
I can reproduce the issue, I'm experiencing the same symptoms.

**Comment by jamesmk** [comment] 2019-02-04 17:36
@nlively @Shigawire What versions of Fae are you seeing this issue on?

**Comment by Shigawire** [comment] 2019-02-04 19:15
@jamesmk The latest (2.0)

**Comment by jamesmk** [comment] 2022-07-17 23:18
We still haven't been able to reproduce this issue across the many Fae CMS' we manage. I'm going to close this one out, but feel free to re-open if there's example code or an app the reproduces this issue.

thanks

**Closed by jamesmk** 2022-07-17 23:18 UTC
Labels: requesting feedback
